"use client";
export default function Template3({ postTitle, category, orgName, cyberName }) {
  return (
    <div className="flex flex-col items-center border-4 border-blue-500 p-4 rounded-lg bg-white">
      <h2 className="text-lg font-semibold mb-1">{category} 2025</h2>
      <h1 className="text-3xl font-bold text-red-600 mb-3">{postTitle}</h1>
      <p className="text-gray-600">Organised by {orgName}</p>
      <p className="mt-4 text-sm text-gray-500">Generated by: {cyberName}</p>
    </div>
  );
}