"use client";

export default function Template2({ postTitle, category, orgName, cyberName }) {
  return (
    <div className="flex flex-col items-center bg-gradient-to-b from-blue-100 to-white p-6 rounded-lg">
      <h1 className="text-2xl font-bold text-blue-700 mb-2">{postTitle}</h1>
      <p className="text-gray-700 mb-2 italic">{category}</p>
      <p className="text-gray-600">Organised by {orgName}</p>
      <p className="mt-6 text-gray-500 text-sm">Generated by: {cyberName}</p>
    </div>
  );
}